# Generated by Django 5.2.5 on 2025-09-15 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('validade', models.DateTimeField(default=datetime.datetime(2025, 9, 15, 17, 14, 14, 833565, tzinfo=datetime.timezone.utc))),
                ('tentativas', models.IntegerField(default=0)),
            ],
        ),
    ]
