# Generated by Django 5.2.5 on 2025-09-15 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigocadastro',
            name='validade',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 15, 17, 15, 41, 573528, tzinfo=datetime.timezone.utc)),
        ),
    ]
