# Generated by Django 5.2.6 on 2025-09-19 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_codigocadastro_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigocadastro',
            name='validade',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 19, 15, 50, 35, 522730, tzinfo=datetime.timezone.utc)),
        ),
    ]
