# Generated by Django 5.2.6 on 2025-09-22 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_codigocadastro_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigocadastro',
            name='validade',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 21, 22, 44, 732582, tzinfo=datetime.timezone.utc)),
        ),
    ]
